#!/usr/bin/env python3
"""Regenerate docs/results.md from the committed run artefacts.

    python scripts/make_report.py --result results/scaling/mujoco/scaling.json

The tables in the documentation are generated from the JSON rather than typed,
so a number in the prose cannot drift away from the number in the artefact. If
this script has not been re-run after a new result, the header says so.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# The predecessor study's published held-out numbers.
ORIGINAL = {"cnn_unseen": 0.584, "heuristic_unseen": 0.753,
            "cnn_seen": 0.838, "heuristic_seen": 0.883,
            "angle_heldout_deg": 47.2}


def curve_table(result: dict) -> str:
    lines = [
        "| training scenes | labelled grasps | seen | held-out | gap | angle error (held-out) |",
        "|---|---|---|---|---|---|",
    ]
    for point in sorted(result["points"], key=lambda p: p["train_samples"]):
        seen, unseen = point["seen"], point["unseen"]
        lines.append(
            f"| {point['train_scenes']:,} | {point['train_samples']:,} "
            f"| {seen['rate']:.1%} | {unseen['rate']:.1%} "
            f"| {point['generalisation_gap_pp']:.1f} pp "
            f"| {point['angle']['angle_error_deg_heldout']:.1f} deg |")
    return "\n".join(lines)


def control_table(result: dict) -> str:
    lines = ["| policy | seen | held-out | original study, held-out |", "|---|---|---|---|"]
    for name, control in result.get("controls", {}).items():
        original = ORIGINAL.get(f"{name}_unseen")
        reference = f"{original:.1%}" if original else "-"
        lines.append(f"| {name} (re-run unchanged) | {control['seen']['rate']:.1%} "
                     f"| {control['unseen']['rate']:.1%} | {reference} |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--result", action="append", required=True,
                        help="a scaling.json; repeat for each arm of the experiment")
    parser.add_argument("--throughput", default=None)
    parser.add_argument("--out", default="docs/results.md")
    args = parser.parse_args()

    sections = [
        "# Results",
        "",
        "Generated by `python scripts/make_report.py`. Every number here is read "
        "from a committed artefact under `results/`; none is typed by hand.",
        "",
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
    ]

    for path in args.result:
        result = json.loads(Path(path).read_text())
        dataset = result.get("dataset", {})
        backend = dataset.get("backend", "unknown")
        config = result.get("config", {})
        sections += [
            f"## {backend} arm",
            "",
            f"Dataset `{dataset.get('path', '?')}`: {dataset.get('n_scenes', '?')} scenes, "
            f"{dataset.get('angles_per_scene', '?')} grasps per scene, "
            f"{dataset.get('image_size', '?')} px.",
            f"Training: {config.get('epochs', '?')} epochs at "
            f"{config.get('input_size') or dataset.get('image_size', '?')} px, "
            f"identical at every point. Evaluation: {config.get('eval_episodes', '?')} "
            "episodes per split on the original held-out scenes.",
            "",
            "### The control",
            "",
            "Re-run unchanged. It does not depend on training data, so it should "
            "reproduce the original study. If it does not, every other number here "
            "is suspect.",
            "",
            control_table(result),
            "",
            "### The curve",
            "",
            curve_table(result),
            "",
            "Random guessing scores 45 degrees of orientation error. The original "
            f"study measured {ORIGINAL['angle_heldout_deg']:.1f} degrees on held-out "
            "categories, which is worse than chance.",
            "",
        ]

    if args.throughput:
        from isaacgrasp.throughput import format_table

        comparison = json.loads(Path(args.throughput).read_text())
        sections += ["## Throughput", "", "```", format_table(comparison), "```", ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(sections))
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
