#!/usr/bin/env python3
"""Regenerate docs/results.md from the committed run artefacts.

    python scripts/make_report.py --result results/scaling/mujoco/scaling.json

The tables in the documentation are generated from the JSON rather than typed,
so a number in the prose cannot drift away from the number in the artefact. If
this script has not been re-run after a new result, the header says so.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# The predecessor study's published held-out numbers.
ORIGINAL = {"cnn_unseen": 0.584, "heuristic_unseen": 0.753,
            "cnn_seen": 0.838, "heuristic_seen": 0.883,
            "angle_heldout_deg": 47.2, "bin_spread": 0.070}

BACKEND_NAMES = {"mujoco": "MuJoCo", "isaac": "Isaac Lab"}


def backend_name(result: dict) -> str:
    raw = result.get("dataset", {}).get("backend", "unknown")
    return BACKEND_NAMES.get(raw, raw)


def curve_table(result: dict) -> str:
    lines = [
        "| training scenes | labelled grasps | seen | held-out | gap | angle error (held-out) |",
        "|---|---|---|---|---|---|",
    ]
    for point in sorted(result["points"], key=lambda p: p["train_samples"]):
        seen, unseen = point["seen"], point["unseen"]
        lines.append(
            f"| {point['train_scenes']:,} | {point['train_samples']:,} "
            f"| {seen['rate']:.1%} | {unseen['rate']:.1%} "
            f"| {point['generalisation_gap_pp']:.1f} pp "
            f"| {point['angle']['angle_error_deg_heldout']:.1f} deg |")
    return "\n".join(lines)


def control_table(result: dict) -> str:
    lines = ["| policy | seen | held-out | original study, held-out |", "|---|---|---|---|"]
    for name, control in result.get("controls", {}).items():
        original = ORIGINAL.get(f"{name}_unseen")
        reference = f"{original:.1%}" if original else "-"
        lines.append(f"| {name} (re-run unchanged) | {control['seen']['rate']:.1%} "
                     f"| {control['unseen']['rate']:.1%} | {reference} |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--result", action="append", required=True,
                        help="a scaling.json; repeat for each arm of the experiment")
    parser.add_argument("--throughput", default=None)
    parser.add_argument("--out", default="docs/results.md")
    parser.add_argument("--readme", default=None,
                        help="also fill the RESULTS block in this README")
    parser.add_argument("--figure", default=None,
                        help="path to the curve image, as the README should reference it")
    args = parser.parse_args()

    sections = [
        "# Results",
        "",
        "Generated by `python scripts/make_report.py`. Every number here is read "
        "from a committed artefact under `results/`; none is typed by hand.",
        "",
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
    ]

    for path in args.result:
        result = json.loads(Path(path).read_text())
        dataset = result.get("dataset", {})
        config = result.get("config", {})
        sections += [
            f"## The {backend_name(result)} arm",
            "",
            f"Dataset `{dataset.get('path', '?')}`: {dataset.get('n_scenes', '?')} scenes, "
            f"{dataset.get('angles_per_scene', '?')} grasps per scene, "
            f"{dataset.get('image_size', '?')} px.",
            f"Training: {config.get('epochs', '?')} epochs at "
            f"{config.get('input_size') or dataset.get('image_size', '?')} px, "
            f"identical at every point. Evaluation: {config.get('eval_episodes', '?')} "
            "episodes per split on the original held-out scenes.",
            "",
            "### The control",
            "",
            "Re-run unchanged. It does not depend on training data, so it should "
            "reproduce the original study. If it does not, every other number here "
            "is suspect.",
            "",
            control_table(result),
            "",
            "### The curve",
            "",
            curve_table(result),
            "",
            "Random guessing scores 45 degrees of orientation error. The original "
            f"study measured {ORIGINAL['angle_heldout_deg']:.1f} degrees on held-out "
            "categories, which is worse than chance.",
            "",
        ]

    if args.throughput:
        from isaacgrasp.throughput import format_table

        comparison = json.loads(Path(args.throughput).read_text())
        sections += ["## Throughput", "", "```", format_table(comparison), "```", ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(sections))
    print(f"wrote {out}")

    if args.readme:
        primary = json.loads(Path(args.result[0]).read_text())
        update_readme(Path(args.readme), primary, args.figure)
        print(f"updated {args.readme}")
    return 0


def readme_block(result: dict, figure: str | None) -> str:
    """The README's results section, generated from the artefacts.

    Written between markers so the numbers in the README are the numbers in the
    JSON. A README table maintained by hand drifts from the run that produced
    it, and the drift is invisible until someone tries to reproduce it.
    """
    points = sorted(result["points"], key=lambda p: p["train_samples"])
    first, last = points[0], points[-1]
    controls = result.get("controls", {}).get("heuristic", {})
    dataset = result.get("dataset", {})
    config = result.get("config", {})

    lines = ["## Results", ""]
    if figure:
        lines += [f"![Grasp success and orientation error against training set size]({figure})",
                  ""]

    lines += [
        "### The control, re-run unchanged",
        "",
        "It does not depend on training data, so it should reproduce the original "
        "study. This is the first number to read: if it had come out different, "
        "something in the environment had moved and nothing else here would be "
        "trustworthy.",
        "",
        "| | this run | original study |",
        "|---|---|---|",
    ]
    if controls:
        lines += [
            f"| Heuristic, held-out categories | **{controls['unseen']['rate']:.1%}** "
            f"| {ORIGINAL['heuristic_unseen']:.1%} |",
            f"| Heuristic, seen categories | {controls['seen']['rate']:.1%} "
            f"| {ORIGINAL['heuristic_seen']:.1%} |",
        ]
    reading = result.get("reading", {})
    trends = reading.get("trends", {})

    lines += [
        "",
        f"### The curve, on {backend_name(result)}-generated data",
        "",
        f"Same architecture, same training loop, {config.get('epochs', '?')} epochs at "
        f"{config.get('input_size') or dataset.get('image_size', '?')} px at every point. "
        "Training subsets are nested and the validation set is fixed, so a difference "
        "between points is added data and nothing else.",
        "",
        curve_table(result),
        "",
        f"n = {config.get('eval_episodes', '?')} evaluation episodes per split, on the "
        "original held-out scenes. The 95% intervals are about plus or minus 7 points, "
        "so adjacent points are not individually distinguishable; the trend is the "
        "readable part.",
        "",
        "### What the curve says",
        "",
        f"Over a {last['train_samples'] / first['train_samples']:.0f}x range in training "
        f"data, fitting rate against log2(samples):",
        "",
        "| quantity | slope per doubling | 95% interval | r-squared |",
        "|---|---|---|---|",
    ]
    for key, label in (("seen_success", "Seen-category success"),
                       ("held_out_success", "Held-out success"),
                       ("held_out_angle_error", "Held-out orientation error")):
        trend = trends.get(key)
        if not trend:
            continue
        unit = "deg" if "angle" in key else "pp"
        low, high = trend.get("slope_ci95_pp", [float("nan"), float("nan")])
        interval = ("not available" if low != low
                    else f"{low:+.2f} to {high:+.2f}")
        lines.append(f"| {label} | {trend['slope_per_doubling_pp']:+.2f} {unit} "
                     f"| {interval} | {trend['r_squared']:.2f} |")

    held_trend = trends.get("held_out_success", {})
    low, high = held_trend.get("slope_ci95_pp", [float("nan"), float("nan")])
    bounded = low == low and high == high
    if bounded and low <= 0 <= high:
        verdict = (
            f"Held-out success is **consistent with flat**: its 95% interval runs from "
            f"{low:+.2f} to {high:+.2f} points per doubling, which contains zero. The "
            f"useful half of that is the upper end. Whatever gain more data buys on "
            f"unseen shapes, over this range it is **at most {high:.2f} points per "
            f"doubling**, and closing the {100 * (controls['unseen']['rate'] - last['unseen']['rate']):.0f} "
            f"point distance to the heuristic at that rate would take about "
            f"{(100 * (controls['unseen']['rate'] - last['unseen']['rate']) / high):.0f} "
            f"further doublings.")
    elif bounded and low > 0:
        verdict = (
            f"Held-out success **is rising**, by {low:+.2f} to {high:+.2f} points per "
            f"doubling at 95% confidence. Closing the "
            f"{100 * (controls['unseen']['rate'] - last['unseen']['rate']):.0f} point "
            f"distance to the heuristic would take between "
            f"{(100 * (controls['unseen']['rate'] - last['unseen']['rate']) / high):.0f} "
            f"and {(100 * (controls['unseen']['rate'] - last['unseen']['rate']) / low):.0f} "
            "further doublings.")
    else:
        verdict = (
            f"Held-out success does not resolve: the fitted slope explains "
            f"{held_trend.get('r_squared', float('nan')):.0%} of the scatter.")

    lines += [
        "",
        f"Seen-category success rises. {verdict} Held-out success moved from "
        f"{first['unseen']['rate']:.1%} to {last['unseen']['rate']:.1%} against the "
        f"heuristic's {controls['unseen']['rate']:.1%}, and the gap between seen and "
        f"held-out went from {first['generalisation_gap_pp']:.1f} to "
        f"{last['generalisation_gap_pp']:.1f} points.",
        "",
        f"Orientation error on held-out shapes stayed within "
        f"{max(abs(p['angle']['angle_error_deg_heldout'] - 45.0) for p in points):.1f} "
        f"degrees of the 45 that random guessing scores, at every size measured, and on "
        f"seen categories it did not improve either "
        f"({points[0]['angle']['angle_error_deg_seen']:.1f} degrees at the smallest size, "
        f"{last['angle']['angle_error_deg_seen']:.1f} at the largest). Scored on "
        f"{last['angle']['n_seen']} seen and {last['angle']['n_heldout']} held-out grasps "
        "per point, over the elongated objects where an angle is determinate at all.",
        "",
        f"The sharper measurement is the **bin spread**: the range of predicted grasp "
        f"quality across the twelve gripper angles at the pixel the network chose. It "
        f"falls from {points[0]['angle']['bin_spread']:.2f} to "
        f"{last['angle']['bin_spread']:.2f} across the curve. The first value is an "
        f"undertrained network's noise rather than real angle sensitivity, so the reading "
        f"is that the network's quality estimate becomes progressively **less** sensitive "
        f"to how the gripper is turned as it sees more data, settling near the "
        f"{ORIGINAL['bin_spread']:.3f} the original measured at roughly 27,000 samples. "
        "Predicting the angle-marginal success rate is a minimum of this loss, and more "
        "data finds it more reliably.",
        "",
        "### What this arm does not settle",
        "",
        f"**It tops out below the study it follows up.** The largest point here is "
        f"{last['train_samples']:,} labelled grasps. The original trained on roughly "
        f"27,000 and reported {ORIGINAL['cnn_unseen']:.1%} held-out, which is above every "
        f"point on this curve. So the curve evidently continues upward past where this arm "
        f"reached, and nothing here shows that more data cannot help. What it shows is "
        f"that across a {last['train_samples'] / first['train_samples']:.0f}x range the "
        f"held-out gap did not close and orientation did not leave chance.",
        "",
        "Reaching the original's scale, and the one to two orders of magnitude beyond it "
        "that the Isaac Lab port exists to make affordable, is the experiment this arm "
        "sets up rather than the one it performs. The Isaac backend has not been run.",
        "",
        "Full tables in [docs/results.md](docs/results.md); the raw numbers are in "
        "`results/scaling/` as JSON and CSV.",
    ]
    return "\n".join(lines)


def update_readme(path: Path, result: dict, figure: str | None) -> None:
    text = path.read_text()
    start, end = "<!-- RESULTS -->", "<!-- /RESULTS -->"
    if start not in text or end not in text:
        raise SystemExit(f"{path} has no {start} / {end} markers to fill")
    head = text[: text.index(start) + len(start)]
    tail = text[text.index(end):]
    path.write_text(f"{head}\n{readme_block(result, figure)}\n{tail}")


if __name__ == "__main__":
    raise SystemExit(main())
